"""Add citations to Message model

Revision ID: 27dcab16ce56
Revises: 
Create Date: 2024-08-10 16:41:35.425401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dcab16ce56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('history')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('citations')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
